exporter:
  compose_file: docker-compose-example.yml
  service: exporter
  wait: 1s
  path: /metrics
  allow_empty: false
  disallowed_metrics:
    - example_metric
  metrics:
    - name: pg_up
      type: gauge
      value: 1
    - name: pg_exporter_scrapes_total
      type: counter
      disallowed_labels:
        - not_exist
    - name: pg_database_size_bytes
      labels:
        - datname
    - name: go_gc_duration_seconds
      type: summary
  hooks:
    - name: on-the-machine
      setup:
        - echo "setup on the machine"
      teardown:
        - echo "teardown on the machine"
    - name: in-the-container
      container: postgres
      setup:
        - echo "setup in the container"
        - sleep 3s
        - psql heracles mrlyc -c 'CREATE DATABASE example;'
      teardown:
        - echo "teardown in the container"
