exporter:
  compose_file: docker-compose-example.yml
  service: exporter
  wait: 3s
  path: /metrics
  allow_empty: false
  disallowed_metrics:
    - example_metric
  metrics:
    - name: pg_up
      type: gauge
      value: 1
    - name: pg_exporter_scrapes_total
      type: counter
      disallowed_metrics:
        - not_exist
    - name: pg_database_size_bytes
      labels:
        - datname
    - name: go_gc_duration_seconds
      type: summary
