version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=heracles
      - POSTGRES_USER=mrlyc
      - POSTGRES_DB=example
    networks:
      - postgres_network

  exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://mrlyc:heracles@postgres:5432/example?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

